# Generated by Django 5.0.4 on 2024-06-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_docente_curso_inscripcion_curso_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='LE',
            field=models.IntegerField(null=True, unique=True, verbose_name='Libreta Estudiantil'),
        ),
    ]
