# Generated by Django 5.0.4 on 2024-06-06 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alumno_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.docente'),
        ),
    ]
